### PR TITLE
fix: update file paths to use forward slashes for Windows compatibility

### PR DESCRIPTION
**Pull request by alan-agius4**

### CODE REVIEW

**Review by codepunkt — APPROVED** [review]
Thanks, that's helpful!

**Comment by codepunkt** [comment]
Seems I gotta fix the GitHub actions. Tests run fine locally 👍🏻

**Comment by codepunkt** [comment]
Released as `3.0.1` - thanks for considering this plugin!

**Comment by alan-agius4** [comment]
Great thanks.

**Pull request merged**
